return {
  -- 'nvim-lualine/lualine.nvim',
  -- dependencies = { 'echasnovski/mini.icons' },
  -- opts = {
  --   options = {
  --     globalstatus = true,
  --   },
  --   extensions = { 'lazy', 'fugitive' },
  --   sections = {
  --     lualine_a = {},
  --     lualine_c = { { 'filename', path = 1 } },
  --     lualine_x = { 'filetype' },
  --   },
  --   -- inactive_sections = {
  --   --   lualine_a = {},
  --   --   lualine_c = { { 'filename', path = 1 } },
  --   --   lualine_x = { 'filetype' },
  --   -- },
  -- },
  -- config = function(_, opts)
  --   require('lualine').setup(opts)
  -- end,
  -- event = 'VimEnter',
  -- lazy = false,
  -- priority = 1001,
}
